package postgres

import (
	"testing"

	"gorm.io/gorm/schema"
)

func Test_DataTypeOf(t *testing.T) {
	type fields struct {
		Config *Config
	}
	type args struct {
		field *schema.Field
	}
	tests := []struct {
		name   string
		fields fields
		args   args
		want   string
	}{
		{
			name: "it should return boolean",
			args: args{field: &schema.Field{DataType: schema.Bool}},
			want: "boolean",
		},
		{
			name: "it should return text -1",
			args: args{field: &schema.Field{DataType: schema.String, Size: -1}},
			want: "text",
		},
		{
			name: "it should return text > 10485760",
			args: args{field: &schema.Field{DataType: schema.String, Size: 12345678}},
			want: "text",
		},
		{
			name: "it should return varchar(100)",
			args: args{field: &schema.Field{DataType: schema.String, Size: 100}},
			want: "varchar(100)",
		},
		{
			name: "it should return varchar(10485760)",
			args: args{field: &schema.Field{DataType: schema.String, Size: 10485760}},
			want: "varchar(10485760)",
		},
		{
			// https://github.com/go-gorm/gorm/issues/7191
			name: "generated:identity renders an identity column (BY DEFAULT)",
			args: args{field: &schema.Field{
				DataType:      schema.Uint,
				GORMDataType:  schema.Uint,
				Size:          64,
				PrimaryKey:    true,
				AutoIncrement: true,
				TagSettings:   map[string]string{"GENERATED": "identity"},
			}},
			want: "bigint GENERATED BY DEFAULT AS IDENTITY",
		},
		{
			name: "generated:identity always renders an ALWAYS identity column",
			args: args{field: &schema.Field{
				DataType:      schema.Uint,
				GORMDataType:  schema.Uint,
				Size:          64,
				PrimaryKey:    true,
				AutoIncrement: true,
				TagSettings:   map[string]string{"GENERATED": "identity always"},
			}},
			want: "bigint GENERATED ALWAYS AS IDENTITY",
		},
		{
			name: "generated:always identity is order independent",
			args: args{field: &schema.Field{
				DataType:     schema.Int,
				GORMDataType: schema.Int,
				Size:         32,
				TagSettings:  map[string]string{"GENERATED": "always identity"},
			}},
			want: "integer GENERATED ALWAYS AS IDENTITY",
		},
		{
			name: "generated:<expr> renders a STORED computed column",
			args: args{field: &schema.Field{
				DataType:    "numeric",
				TagSettings: map[string]string{"GENERATED": "price * quantity"},
			}},
			want: "numeric GENERATED ALWAYS AS (price * quantity) STORED",
		},
		{
			name: "generated:<expr> keeps commas inside the expression",
			args: args{field: &schema.Field{
				DataType:    schema.String,
				Size:        -1,
				TagSettings: map[string]string{"GENERATED": "coalesce(first_name, last_name)"},
			}},
			want: "text GENERATED ALWAYS AS (coalesce(first_name, last_name)) STORED",
		},
		{
			name: "a bare generated tag is ignored",
			args: args{field: &schema.Field{
				DataType:      schema.Uint,
				GORMDataType:  schema.Uint,
				Size:          64,
				AutoIncrement: true,
				TagSettings:   map[string]string{"GENERATED": "GENERATED"},
			}},
			want: "bigserial",
		},
		{
			name: "a lowercase generated expression is not mistaken for a bare tag",
			args: args{field: &schema.Field{
				DataType:    "numeric",
				TagSettings: map[string]string{"GENERATED": "generated"},
			}},
			want: "numeric GENERATED ALWAYS AS (generated) STORED",
		},
		{
			name: "it should still convert a plain custom type to bigserial for an auto increment field",
			args: args{field: &schema.Field{
				DataType:      "bigint",
				GORMDataType:  schema.Uint,
				AutoIncrement: true,
				Size:          64,
			}},
			want: "bigserial",
		},
		{
			name: "it should keep an explicit bigserial type for an auto increment field",
			args: args{field: &schema.Field{
				DataType:      "bigserial",
				GORMDataType:  schema.Uint,
				AutoIncrement: true,
				Size:          64,
			}},
			want: "bigserial",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dialector := Dialector{
				Config: tt.fields.Config,
			}
			if got := dialector.DataTypeOf(tt.args.field); got != tt.want {
				t.Errorf("DataTypeOf() = %v, want %v", got, tt.want)
			}
		})
	}
}
