name: tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  run-tests:
    strategy:
      matrix:
        go: ['1.23.0']
        platform: [ubuntu-latest]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: gorm
          POSTGRES_PASSWORD: gorm
          POSTGRES_DB: gorm
        ports:
          - 9920:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v7
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v7

      # Run build of the application
    - name: Run build
      run: go build .

    - name: Run tests
      env:
        POSTGRES_DSN: host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable
      run: go test -race -count=1 -v ./...
